src/app/menus/urls.py
from django.urls import path

import app.menus.views as views

app_name = 'menus'
urlpatterns = [
    path('main/', views.menu_list, name='main'),
    path('<str:global_menu_url_name>/', views.menu_detail, name='menu_detail'),
    path('<str:global_menu_url_name>/<str:section_url_slug>/', views.menu_section_detail, name='section_menu_detail'),
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.menus.urls'))
]

src/app/menus/models.py
from django.db import models


class Menu(models.Model):
    url_name = models.CharField(max_length=30, null=False, unique=True)
    verbose_name = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.verbose_name


class MenuSection(models.Model):
    verbose_name = models.CharField(max_length=100)
    global_menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='sections')
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    url_slug = models.SlugField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.verbose_name

src/app/menus/views.py
from django.shortcuts import render

from app.menus.models import Menu, MenuSection


def menu_list(request):
    menus = Menu.objects.all()
    context = {'menus': [menu.url_name for menu in menus]}
    return render(request, "menus/main.html", context)


def menu_detail(request, global_menu_url_name):
    context = {'menus': [global_menu_url_name, ]}
    return render(request, "menus/main.html", context)


def menu_section_detail(request, global_menu_url_name, section_url_slug):
    context = {'menus': [global_menu_url_name, ], 'active_section_url_slug': section_url_slug}
    return render(request, "menus/main.html", context)

src/app/menus/templates/menus/main.html
{% load menus_extras %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
    <link href="{% static 'menus/css/menus.css' %}" rel="stylesheet">
    <link rel="icon" href="data:;base64,=">
</head>
<body>
<h1>UpTrader</h1>

{% for menu in menus %}
    {% draw_menu menu %}
{% endfor %}

</body>
<script src="{% static 'menus/js/menus.js' %}" type="text/javascript"></script>
</html>

src/app/menus/templates/menus/menu_sections.html
{% load menus_extras %}
<li>
    <span class="caret {% if section_data.children %}children{% endif %} {% if section_data.is_opened %}caret-down{% endif %}"></span>
    <a class="{% if section.url_slug == active_section_url_slug %}section-active{% endif %}" href="{% url 'menus:section_menu_detail' menu.url_name section.url_slug %}">
        {{ section.verbose_name }}
    </a>
    {% if section_data.children %}
        <ul class="nested {% if section_data.is_opened %}active{% endif %}">
            {% for child in section_data.children %}
                {% with section=child.keys|to_list|hash:0 section_data=child.values|to_list|hash:0 template_name="menus/menu_sections.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}
        </ul>
    {% endif %}
</li>

src/app/menus/templates/menus/menu_single.html
<div class="menu container">
    <h3>{{ menu.verbose_name }}</h3>
    <hr>
    <ul class="menu">
        {% for section, section_data in sections_mapping.items %}
            {% include 'menus/menu_sections.html' %}
        {% endfor %}
    </ul>
</div>